from .fn_classifier import Wav2Vec2Classifier as Wav2Vec2FnClassifier
from .cnn.wav2vec_cnn_classifier import Wav2Vec2CnnClassifier
from .cnn.spectrogram_cnn_classifier import SpectrogramCnnClassifier
from .transformer.transformer_classifier import TransformerClassifier